version: "3.8"
services:
  db:
    image: mysql
    container_name: subscriber-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=subscriber
    networks:
      - subscriber

networks:
  subscriber:
