POST https://127.0.0.1:8000/api/auth/hello
Content-Type: application/json
#Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NDMxOTUzMzQsImV4cCI6MTY0NTc4NzMzNCwicm9sZXMiOlsiUk9MRV9BRE1JTiJdLCJlbWFpbCI6ImF3b2pjaWtAYWttLXdlYi5wbCJ9.Pi5_CB9Y7CwBk-EejyVBpJTYvg32zPevVYvnHRoAwNthvbPB87TEfeo0GZcD2KnUJMh7fybGrNRi0X7QXxR92Gyk0jtcVIqYVpYRdKymbuk9aLKebM5bt1yQxOWLIIFKsd7AADNG0K5egPTes3WiSw9nFjPELwccd0Py8nVneA68I_fUTsyxalRECQnXkusfXx1UigamXg6ylSQa73qSrr81qLkaRx-425oAL2QrhkFpr6kFb6p3Ooa4sZWigjpMYGgMw0kUaXOvggue8RIwSiYnOV3YXFfUePq1pjSht9pCCdLdkfSzOMdNnbBOaR55Rr8TTNcHPi4niU4uQX07eEBwxxv_ZE9Oigks0-TgDkgY7bCLKucuDccrSPcpW4eHJvuox9p_e1FRJ8mZe0JglQIfbouO4rTImAaDMcqCKsuII9qDDfzkxcbUUBGHM3WblaT_DuU1W_cYIJ-mvV_UInth-zmc2Uv7fes-eNBb6BUVZ9EAToHmetpuCdcMOSYgsd0OYEIdLt2agukNzK9Hc1h6xn2vzOTfLjtyyjrQy9WslqNu-p0EfXCRr_ho9IawaVeI-arCm1JxTh2C_VgxAYfMWJUWuKzKfLeFn8lSyofvywA8EThVYPmLhqnJGCkXOfF5Q3JV2KwJLqhv-t4Qa8u17y5oOR0sioER2IKczRQ

{
  "email": "user1@test.com",
  "password": "test"
}


